config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv tox:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-fuchsia-okapi.sh
        container: qc.doc_foggy-fuchsia-sheepdog
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv tox:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-rose-giraffe.sh
        container: qc.sec_nerdy-ruby-iguana
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-buff-shrew.sh
        container: qc.sty_greasy-persimmon-sparrow
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv tox:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-fuchsia-jackal.sh
        container: qc.uni_sunny-cornflower-ocelot
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cinnabar-jaguar.sh
        container: qc.ver_sleepy-goldenrod-crane
timeout: 5400
