name: Software Quality Assurance as a Service

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    name: Quality Assessment & Awarding
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            submodules: true          
            fetch-depth: 0            

        - name: Quality Tests
          uses: eosc-synergy/sqaaas-assessment-action@v2
          with:
            repo: 'https://github.com/HPCI-Lab/yProv.git'
            branch: 'main'

        - name: Install pytest
          run: python3 -m pip install pytest

        - name: UniTests
          run: python3 -m pytest -v
        
        
  
  
