name: Software Quality Assurance as a Service

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    name: Quality Assessment & Awarding
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            submodules: true          
            fetch-depth: 0            

        - name: Quality Tests
          uses: eosc-synergy/sqaaas-assessment-action@v2
          with:
            repo: 'https://github.com/HPCI-Lab/yProv.git'
            branch: 'main'

        - name: Install pytest
          run: python3 -m pip install pytest

        - name: Installa ngrok
          run: curl -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
               unzip ngrok-stable-linux-amd64.zip

        - name: Avvia ngrok per esporre localhost:3000
          run: ./ngrok http 3000

        - name: UniTests
          run: export NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
               python3 -m pytest --base-url="$NGROK_URL/api/v0/auth" -v

        - name: Print out payload
          run: cat workflow_validation_step.json



         

     
        
        
  
  
